name: pos_app
description: "Cross-platform POS app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core libraries
  flutter_riverpod: ^2.6.1     # Scalable state management (preferred over Provider)
  go_router: ^14.8.1           # Declarative navigation and deep linking

  # Offline storage
  hive: ^2.2.3                 # Fast NoSQL storage for offline use
  hive_flutter: ^1.1.0         # Hive extensions for Flutter integration
  path_provider: ^2.1.5        # Access device file system paths

  # Firebase / Firestore
  firebase_core: ^3.12.1       # Required for initializing Firebase
  cloud_firestore: ^5.6.5      # Access Firestore (remote DB)
  firebase_auth: ^5.5.1        # Required for authentication through Firebase

  # UI
  cupertino_icons: ^1.0.8      # iOS-style icons

  # App info
  package_info_plus: ^4.0.2

  # DateFormat
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0         # Recommended linting rules
  build_runner: ^2.4.15         # Code generation runner
  hive_generator: ^2.0.1        # Generates Hive model adapters

flutter:
  uses-material-design: true

  assets:
    - assets/images/