// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnZchzl44u-zKGORamNsHrzjslRADCpo',
    appId: '1:485743774882:web:c3356eb3efdbe29ea59bfb',
    messagingSenderId: '485743774882',
    projectId: 'bub-sams-pos',
    authDomain: 'bub-sams-pos.firebaseapp.com',
    storageBucket: 'bub-sams-pos.firebasestorage.app',
    measurementId: 'G-7EKCX4HX01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvK4Fz6YYrnRv18nCv6oRzVcYQV5FjlPA',
    appId: '1:485743774882:android:a9a56b2db1d789b1a59bfb',
    messagingSenderId: '485743774882',
    projectId: 'bub-sams-pos',
    storageBucket: 'bub-sams-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTGZifmyBdjFh1BOlZFwnGOimt_pw-kc',
    appId: '1:485743774882:ios:0def5675b91c0c39a59bfb',
    messagingSenderId: '485743774882',
    projectId: 'bub-sams-pos',
    storageBucket: 'bub-sams-pos.firebasestorage.app',
    iosBundleId: 'juliane.json.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTGZifmyBdjFh1BOlZFwnGOimt_pw-kc',
    appId: '1:485743774882:ios:0def5675b91c0c39a59bfb',
    messagingSenderId: '485743774882',
    projectId: 'bub-sams-pos',
    storageBucket: 'bub-sams-pos.firebasestorage.app',
    iosBundleId: 'juliane.json.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqnZchzl44u-zKGORamNsHrzjslRADCpo',
    appId: '1:485743774882:web:bd8a01c47e3a659ea59bfb',
    messagingSenderId: '485743774882',
    projectId: 'bub-sams-pos',
    authDomain: 'bub-sams-pos.firebaseapp.com',
    storageBucket: 'bub-sams-pos.firebasestorage.app',
    measurementId: 'G-SFE32G37Y4',
  );
}
